DOC Document jQuery changes
silverstripe/developer-docs pull request #108
Opened 2022-10-26 21:24 UTC by GuySartorelli

Documents the jQuery upgrade

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1351

2022-10-28 03:14 UTC, PRO-BROS commented
Very well. Facing same issue but now resolved on my [site](https://prhocoding.com/)

2022-10-28 06:40 UTC, michalkleiner commented on en/04_Changelogs/4.12.0.md
> +While it is best practice to stop using any deprecated API, you should be able to just do a quick search through your backend javascript and replace anything which the list marks as _removed_ from jQ
for consistency...

```suggestion
While it is best practice to stop using any deprecated API, you should be able to just do a quick search through your back-end javascript and replace anything which the list marks as _removed_ from jQuery - everything else was deprecated but is still present and working for the time being.
```

2022-10-28 06:40 UTC, michalkleiner approved these changes

2022-10-30 20:35 UTC, GuySartorelli commented on en/04_Changelogs/4.12.0.md
> +While it is best practice to stop using any deprecated API, you should be able to just do a quick search through your backend javascript and replace anything which the list marks as _removed_ from jQ
Done

2022-10-30 21:31 UTC, michalkleiner commented
@GuySartorelli not sure if this can be merged on its own before the other PRs are merged so leaving this with you.

2022-10-30 21:36 UTC, GuySartorelli commented
Yeah I'd hold off merging until the actual change is merged. It's in peer review, so whoever reviews the main work will merge this as well. 👍

2022-11-01 00:16 UTC, emteknetnz requested changes

2022-11-01 00:16 UTC, emteknetnz commented on en/04_Changelogs/4.12.0.md
> +We've upgrade jQuery in the CMS from 1.7 to 3.6. Note that this won't affect your front-end at all unless you've been using back-end javascript in your front-end, which is heavily discouraged.
```suggestion
We've upgraded jQuery in the CMS from 1.7 to 3.6. Note that this won't affect your front-end at all unless you've been using back-end javascript in your front-end, which is heavily discouraged.
```

2022-11-01 00:16 UTC, emteknetnz commented on en/04_Changelogs/4.12.0.md
> +jQuery provide [a list of deprecated API](https://api.jquery.com/category/deprecated/) which also marks any API which has been removed. Most of these have recommendations for replacing them as well,
```suggestion
jQuery provides [a list of deprecated API](https://api.jquery.com/category/deprecated/) which also marks any API which has been removed. Most of these have recommendations for replacing them as well, so updating your code should be pretty straight forward.
```

2022-11-01 00:16 UTC, emteknetnz commented on en/04_Changelogs/4.12.0.md
> +The only change to behaviour we've had to make to accomodate jQuery's breaking changes was with entwine's `onadd` and `onmatch` handlers. jQuery has made substantial changes to its internal functiona
```suggestion
The only change to behaviour we've had to make to accommodate jQuery's breaking changes was with entwine's `onadd` and `onmatch` handlers. jQuery has made substantial changes to its internal functionality, especially in regards to how it adds elements to the DOM, so we had to change with it. Entwine used to change jQuery's internal functionality to fire events synchronously when adding elements to the DOM. It now uses a `MutationObserver` to detect elements being added to the DOM, which means the events are fired asynchronously.
```

2022-11-01 00:22 UTC, GuySartorelli commented on en/04_Changelogs/4.12.0.md
> +The only change to behaviour we've had to make to accomodate jQuery's breaking changes was with entwine's `onadd` and `onmatch` handlers. jQuery has made substantial changes to its internal functiona
Done

2022-11-01 00:22 UTC, GuySartorelli commented on en/04_Changelogs/4.12.0.md
> +jQuery provide [a list of deprecated API](https://api.jquery.com/category/deprecated/) which also marks any API which has been removed. Most of these have recommendations for replacing them as well,
Done

2022-11-01 00:22 UTC, GuySartorelli commented on en/04_Changelogs/4.12.0.md
> +We've upgrade jQuery in the CMS from 1.7 to 3.6. Note that this won't affect your front-end at all unless you've been using back-end javascript in your front-end, which is heavily discouraged.
Done

2022-11-01 00:37 UTC, emteknetnz approved these changes

2022-11-01 04:27 UTC, merged