DOC Update references to PHP versions
silverstripe/developer-docs pull request #190
Opened 2023-03-20 03:00 UTC by GuySartorelli

Found some inconsistent/inaccurate/unnecessary references to PHP versions in the docs

## Issue
- https://github.com/silverstripe/developer-docs/issues/164

2023-03-20 03:01 UTC, GuySartorelli commented on en/00_Getting_Started/00_Server_Requirements.md
> -| 5.0 +                    | 8.1 - 8.2   | Unreleased       |
This would get outdated quickly - and we don't want to update CMS 4 docs when we do stuff in CMS 5.

2023-03-20 03:01 UTC, GuySartorelli commented on en/00_Getting_Started/00_Server_Requirements.md
> +* PHP >=7.4, <8.2
PHP 8.2 is officially _unsupported_ in CMS4. May as well make that explicitly clear.

2023-03-21 20:51 UTC, emteknetnz requested changes

2023-03-21 20:51 UTC, emteknetnz commented on en/00_Getting_Started/00_Server_Requirements.md
> +* PHP >=7.4, <8.2
```suggestion
* PHP >=7.4, <=8.1
```
Is a little more intuitive

2023-03-21 21:35 UTC, GuySartorelli commented on en/00_Getting_Started/00_Server_Requirements.md
> +* PHP >=7.4, <8.2
Done

2023-04-12 21:40 UTC, emteknetnz approved these changes

2023-04-12 21:40 UTC, merged