DOC Changelog for SearchContext::getQuery()  parameter
silverstripe/developer-docs pull request #294
Opened 2023-07-04 02:58 UTC by sabina-talipova

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10831

2023-07-04 22:16 UTC, emteknetnz requested changes

2023-07-04 22:16 UTC, emteknetnz commented on en/04_Changelogs/5.1.0.md
> +- Changed parameter type in [`SilverStripe\ORM\Search\SearchContext::getQuery()`](api:DSilverStripe\ORM\Search\SearchContext::getQuery()) for `$limit` from dynamic to `array|null|string`. In CMS 6 me
```suggestion
- Passing an argument for `$limit` that is not `array|string|null` in [`SilverStripe\ORM\Search\SearchContext::getQuery()`](api:SilverStripe\ORM\Search\SearchContext::getQuery()) will throw a deprecation warning. In CMS 6 the parameter type will be changed from dynamic to `array|string|null`.
```

2023-07-04 23:13 UTC, sabina-talipova commented on en/04_Changelogs/5.1.0.md
> +- Changed parameter type in [`SilverStripe\ORM\Search\SearchContext::getQuery()`](api:DSilverStripe\ORM\Search\SearchContext::getQuery()) for `$limit` from dynamic to `array|null|string`. In CMS 6 me
Updated

2023-07-05 05:20 UTC, emteknetnz approved these changes

2023-07-05 05:20 UTC, merged