DOC Document new EagerLoadedDataList
silverstripe/developer-docs pull request #305
Opened 2023-07-24 01:52 UTC by GuySartorelli

Documents changes in https://github.com/silverstripe/silverstripe-framework/pull/10869

## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/10864

2023-07-24 01:55 UTC, GuySartorelli commented on en/02_Developer_Guides/00_Model/02_Relations.md
> +Eager loading supports all relationship types.
No need to specify - all relationship types is all relationship types. Having an explicit list makes it prone to becoming out-of-date.

2023-07-25 02:37 UTC, emteknetnz approved these changes

2023-07-25 03:26 UTC, emteknetnz requested changes
Actually may need to change `EagerLoadedDataList` if we rename the class

2023-08-03 03:33 UTC, emteknetnz approved these changes

2023-08-03 03:34 UTC, merged