DOC Add session-manager documentation
silverstripe/developer-docs pull request #325
Opened 2023-08-14 05:16 UTC by emteknetnz

Issue https://github.com/silverstripe/developer-docs/issues/322

2023-08-14 23:43 UTC, GuySartorelli requested changes
There's a few minor problems with links, but otherwise looks good.

Please target the `5.0` branch so this can take effect immediately.

2023-08-14 23:43 UTC, GuySartorelli commented on en/02_Developer_Guides/18_Cookies_And_Sessions/03_Managing_Sessions.md
> +Read [Saved User Logins](https://docs.silverstripe.org/en/developer_guides/security/member/#saved-user-logins) to learn how to configure the "Keep me signed in" feature for your members.
```suggestion
Read [Saved User Logins](/developer_guides/security/member/#saved-user-logins) to learn how to configure the "Keep me signed in" feature for your members.
```

2023-08-14 23:43 UTC, GuySartorelli commented on en/02_Developer_Guides/18_Cookies_And_Sessions/03_Managing_Sessions.md
> +   (through [`LoginSessionMiddleware`](api:(api:SilverStripe\SessionManager\Middleware\LoginSessionMiddleware)).
```suggestion
   (through [`LoginSessionMiddleware`](api:SilverStripe\SessionManager\Middleware\LoginSessionMiddleware)).
```

2023-08-14 23:43 UTC, GuySartorelli commented on en/02_Developer_Guides/18_Cookies_And_Sessions/03_Managing_Sessions.md
> +Alternatively, you could call [`Permission::check()`](api:SilverStripe\Security\Permission::check()) to validate if the member has a predefined CMS permission. If you need even more granular permissi
```suggestion
Alternatively, you could call [`Permission::check()`](api:SilverStripe\Security\Permission::check()) to validate if the member has a predefined CMS permission. If you need even more granular permissions, you can implement a [`PermissionProvider`](/developer_guides/security/permissions/#permissionprovider) to define your own custom permissions.
```

2023-08-15 03:55 UTC, emteknetnz commented on en/02_Developer_Guides/18_Cookies_And_Sessions/03_Managing_Sessions.md
> +   (through [`LoginSessionMiddleware`](api:(api:SilverStripe\SessionManager\Middleware\LoginSessionMiddleware)).
Updated

2023-08-15 03:55 UTC, emteknetnz commented on en/02_Developer_Guides/18_Cookies_And_Sessions/03_Managing_Sessions.md
> +Alternatively, you could call [`Permission::check()`](api:SilverStripe\Security\Permission::check()) to validate if the member has a predefined CMS permission. If you need even more granular permissi
Updated

2023-08-15 03:55 UTC, emteknetnz commented on en/02_Developer_Guides/18_Cookies_And_Sessions/03_Managing_Sessions.md
> +Read [Saved User Logins](https://docs.silverstripe.org/en/developer_guides/security/member/#saved-user-logins) to learn how to configure the "Keep me signed in" feature for your members.
Updated

2023-08-15 04:05 UTC, emteknetnz commented
closed in favour of https://github.com/silverstripe/developer-docs/pull/327

2023-08-15 04:05 UTC, closed without merging