DOC Performance improvements for changelog
silverstripe/developer-docs pull request #333
Opened 2023-08-23 05:47 UTC by emteknetnz

Issue https://github.com/silverstripe/developer-docs/issues/330

2023-08-23 21:57 UTC, GuySartorelli reviewed
Note: I'm not doing a full review, this is just some questions I had in passing.

2023-08-23 21:57 UTC, ChloeSartorelli commented on en/04_Changelogs/5.1.0.md
> +- DataList::byIDs() - 198% faster - (0.0608s vs 0.1812s)
How many IDs were being passed in? That is likely a factor.

2023-08-23 21:57 UTC, ChloeSartorelli commented on en/04_Changelogs/5.1.0.md
> +  - ManyManyThroughList::foreignIDFilter() - 27% faster (0.6901s vs (0.8766s)
How did you test this? I'm guessing you didn't just call `foreignIDFilter()`?

2023-08-24 00:02 UTC, emteknetnz commented on en/04_Changelogs/5.1.0.md
> +- DataList::byIDs() - 198% faster - (0.0608s vs 0.1812s)
10K - I've linked to the test setup in the description - https://github.com/silverstripe/silverstripe-framework/issues/10860#issue-1790646019

2023-08-24 00:03 UTC, emteknetnz commented on en/04_Changelogs/5.1.0.md
> +  - ManyManyThroughList::foreignIDFilter() - 27% faster (0.6901s vs (0.8766s)
I've linked to the test setup in the description - https://github.com/silverstripe/silverstripe-framework/pull/10904#issue-1838704020

2023-08-24 00:04 UTC, GuySartorelli commented on en/04_Changelogs/5.1.0.md
> +- DataList::byIDs() - 198% faster - (0.0608s vs 0.1812s)
Ahh okay. The way this reads to me right now is that there were 10,000 records in the database and an unspecified number being passed into the method. Might be worth explicitly stating that the 10,000 IDs were being passed into the method.

2023-08-24 00:05 UTC, GuySartorelli commented on en/04_Changelogs/5.1.0.md
> +  - ManyManyThroughList::foreignIDFilter() - 27% faster (0.6901s vs (0.8766s)
Might be worth being explicit about the test, something like "This was tested by passing {x number} IDs into the `forForeignID()` method of each list class, then executing the query"

2023-08-28 00:32 UTC, emteknetnz commented on en/04_Changelogs/5.1.0.md
> +- DataList::byIDs() - 198% faster - (0.0608s vs 0.1812s)
Updated

2023-08-28 00:33 UTC, emteknetnz commented on en/04_Changelogs/5.1.0.md
> +  - ManyManyThroughList::foreignIDFilter() - 27% faster (0.6901s vs (0.8766s)
Updated, I omitted the 'then executing the query' bit cos I'm "sharing" the text with byIDs() - however I don't think we need to be that pedantic here, I think the message of "made the method run faster" is clear

2023-08-28 11:40 UTC, maxime-rainville requested changes
Maybe this is just me, but I'm not a big fan of the "X% faster" metric in this context. I think its difficult to understand what we are talking about.

I would rather say that the "response time has been reduced by X%".

2023-08-28 21:48 UTC, emteknetnz commented
As discussed offline, we'll keep the % faster language since it's more commonly used and easier to say and easiest to understand that it's a "good thing", though it's less "grammatically correct".  Saying that query time has been reduced could be misinterpreted as being a "bad" thing since the word "reduced" is generally negative. Using the word "faster" make it more immediately obvious that it's positive.

e.g.

DataList::byIDs() - 198% faster - (0.0608s vs 0.1812s)

vs

DataList::byIDs() - query time has been reduced by 66% - (0.0608s vs 0.1812s)

2023-08-31 07:05 UTC, maxime-rainville approved these changes

2023-08-31 07:05 UTC, merged