DOC Update bug reports page
silverstripe/developer-docs pull request #357
Opened 2023-10-04 03:12 UTC by GuySartorelli

## Issue
- https://github.com/silverstripeltd/product-issues/issues/783

2023-10-04 03:16 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
> - * Note that [documentation issues](https://github.com/silverstripe/developer-docs/issues) are tracked in the "developer-docs" repository.
Which module the issue belongs to moved to the next section

2023-10-04 03:16 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
> -   and the enhancement is likely to be implemented in the next couple of months.
No need to put this here, there's a whole section for this further down.

2023-10-04 03:16 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
> +[/alert]
Make this really prominent to reduce the risk of public security issues

2023-10-04 03:16 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
> +[/warning]
Make this more prominent in case anyone missed it the first time

2023-10-04 03:16 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
> -* [All issues across modules](https://www.silverstripe.org/community/contributing-to-silverstripe/github-all-core-issues)
This section has no information in it... I don't know what the purpose of it was so I removed it outright.

2023-10-04 03:16 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
> -and searches across all Silverstripe CMS modules in there.
This isn't a "how to find bugs that might affect my project" page, and the tool noted here isn't maintained.

2023-10-04 03:16 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
The URLs here for the issue tracker are probably not the best URLs to use. There's a discussion on this in the CMS Squad slack channel, and in the meantime I'll just leave them as is.

2023-10-11 22:50 UTC, emteknetnz requested changes

2023-10-11 22:50 UTC, emteknetnz commented on en/05_Contributing/00_Issues_and_Bugs.md
> + * Describe the steps required to reproduce your issue, and the expected outcome. Example code, screenshots, and screencasts can help here.
```suggestion
 * Describe the steps required to reproduce your issue, and the expected outcome. Example code, screenshots, and videos can help here.
```

2023-10-11 22:50 UTC, emteknetnz commented on en/05_Contributing/00_Issues_and_Bugs.md
> +write it for you. Any "wishlist" type issues without code attached can be
I think "use the forum" was the standard place to talk about feature requests?

2023-10-12 02:06 UTC, GuySartorelli commented on en/05_Contributing/00_Issues_and_Bugs.md
> + * Describe the steps required to reproduce your issue, and the expected outcome. Example code, screenshots, and screencasts can help here.
Done

2023-10-12 20:27 UTC, emteknetnz approved these changes

2023-10-12 20:27 UTC, merged