DOC Move labels into issues page
silverstripe/developer-docs pull request #359
Opened 2023-10-05 21:53 UTC by GuySartorelli

The labels aren't applied to PRs, but they are applied to issues. Makes sense to mention them in the page about issues.

## Issue
- https://github.com/silverstripeltd/product-issues/issues/783

2023-10-11 23:08 UTC, emteknetnz approved these changes

2023-10-12 20:28 UTC, emteknetnz requested changes
Merge conflict

2023-10-12 20:42 UTC, GuySartorelli commented
Rebased and resolved conflicts

2023-10-12 21:38 UTC, emteknetnz approved these changes

2023-10-12 21:38 UTC, merged