DOCS Update security issues docs
silverstripe/developer-docs pull request #371
Opened 2023-10-11 02:02 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/developer-docs/issues/360

2023-10-11 22:43 UTC, emteknetnz requested changes
Also change the commit / pr title prefix from DOCS to DOC

2023-10-11 22:43 UTC, emteknetnz commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Perform an initial assessment of the report. If it is obviously spam or otherwise invalid, reply to the reporter thanking them for their efforts and explaining that we won't be handling this as a
```suggestion
1. Perform an initial assessment of the report. If the report does not qualify as a security issue then reply to the reporter thanking them for their efforts and explaining that we won't be handling this as a security issue.
```

2023-10-11 22:43 UTC, emteknetnz commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Perform a criticality assessment to determine how severe the issue is and if it can be replicated.
```suggestion
1. Perform an assessment to determine how severe the issue is and if it can be replicated.
```

2023-10-11 22:43 UTC, emteknetnz commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Clarify who picks up and owns the issue (assign in GitHub).
```suggestion
1. Clarify who picks up the issue for an initial assessment (assign in GitHub).
```

2023-10-11 22:43 UTC, emteknetnz commented on en/05_Contributing/17_Managing_Security_Issues.md
> +    - The owner can be separate from the developer resolving the issue. Their primary responsibility is to ensure the issue keeps moving through the process correctly.
```suggestion
    - The developer doing an initial assessment on the issue can be separate from the developer implementing a fix for the issue.
```

2023-10-11 22:43 UTC, emteknetnz commented on en/05_Contributing/17_Managing_Security_Issues.md
> +- If the silverstripe-security GitHub organisation doesn't have a pre-existing private repo for the module that needs to be fixed, create one and push the public git history to it. You cannot create
```suggestion
- If the silverstripe-security GitHub account doesn't have a pre-existing private repo for the module that needs to be fixed, do not create a fork because you cannot create a private fork of a private repo. Instead create a new repo on the silverstripe-security account and push the public git history to it.
```

2023-10-11 22:50 UTC, GuySartorelli commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Clarify who picks up and owns the issue (assign in GitHub).
The idea is more than just doing the initial assessment - they're the person who communicates with the reporter, applies for a CVE, etc.

2023-10-11 22:51 UTC, GuySartorelli commented on en/05_Contributing/17_Managing_Security_Issues.md
> +- If the silverstripe-security GitHub organisation doesn't have a pre-existing private repo for the module that needs to be fixed, create one and push the public git history to it. You cannot create
Agreed with all except changing "organisation" to "account" - it's not an account like mine or yours. It's an organisation in GitHub terminology.

2023-10-11 23:06 UTC, emteknetnz commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Clarify who picks up and owns the issue (assign in GitHub).
ok, "picks up" and "owns" are the same thing, so get rid of " and owns"

2023-10-12 01:58 UTC, GuySartorelli commented on en/05_Contributing/17_Managing_Security_Issues.md
> +- If the silverstripe-security GitHub organisation doesn't have a pre-existing private repo for the module that needs to be fixed, create one and push the public git history to it. You cannot create
Done, but also left public as public - the point is that we can't make a private security fork of our public core/supported modules.

2023-10-12 01:58 UTC, GuySartorelli commented on en/05_Contributing/17_Managing_Security_Issues.md
> +    - The owner can be separate from the developer resolving the issue. Their primary responsibility is to ensure the issue keeps moving through the process correctly.
Reworded a bit, since this suggestion assumed the person who picks up the issue was only doing the initial assessment.

2023-10-12 01:58 UTC, GuySartorelli commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Clarify who picks up and owns the issue (assign in GitHub).
Done and added a clarification similar to my comment above to avoid ambiguity.

2023-10-12 01:58 UTC, GuySartorelli commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Perform a criticality assessment to determine how severe the issue is and if it can be replicated.
Yeah I didn't like "criticality" when it was first added either lol.
Done.

2023-10-12 01:58 UTC, GuySartorelli commented on en/05_Contributing/17_Managing_Security_Issues.md
> +1. Perform an initial assessment of the report. If it is obviously spam or otherwise invalid, reply to the reporter thanking them for their efforts and explaining that we won't be handling this as a
Done, but I kept the comma instead of "then" to be more natural.

2023-10-12 20:34 UTC, emteknetnz requested changes
Change the commit/pr-title prefix from DOCS to DOC

2023-10-12 20:38 UTC, GuySartorelli commented
Ahh yup sorry, I missed that the first time.
Cow will accept both, but since it's on me I may as well change it.

Done.

2023-10-12 21:38 UTC, emteknetnz approved these changes

2023-10-12 21:39 UTC, merged