DOC Document new dev admin permissions
silverstripe/developer-docs pull request #399
Opened 2023-11-10 00:30 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/10852

2023-11-10 00:57 UTC, andrewandante requested changes
Couple of typos, I'd add the actual name of the config option because as a dev, that's what I'm scanning for.

I think this page also needs to be updated: https://docs.silverstripe.org/en/5/developer_guides/controllers/builtin_middlewares/

2023-11-10 00:57 UTC, andrewandante commented on en/04_Changelogs/5.2.0.md
> +You can also now optonally implement a `canView()` method on your `BuildTask` implementations to restrict access for specific tasks even further. This means you can grant access to _some_ tasks to sp
```suggestion
You can also now optionally implement a `canView()` method on your `BuildTask` implementations to restrict access for specific tasks even further. This means you can grant access to _some_ tasks to specific users or groups without granting access to _all_ tasks.
```

2023-11-10 00:57 UTC, andrewandante commented on en/04_Changelogs/5.2.0.md
> +Previously, all `/dev/*` routes registered with [`DevelopmentAdmin`](api:SilverStripe\Dev\DevelopmentAdmin) (for example `/dev/tasks/MyBuildTask`) could only be access by administrator users, and thi
```suggestion
Previously, all `/dev/*` routes registered with [`DevelopmentAdmin`](api:SilverStripe\Dev\DevelopmentAdmin) (for example `/dev/tasks/MyBuildTask`) could only be accessed by administrator users, and this couldn't be configured.
```

2023-11-10 00:57 UTC, andrewandante commented on en/04_Changelogs/5.2.0.md
> +Now, all of the controllers which handle these routes that come packaged in a core or supported module have configurable permissions that can be used to grant non-administrative users access to these
```suggestion
Now, all of the controllers which handle these routes that come packaged in a core or supported module have configurable `$init_permissions` that can be used to grant non-administrative users access to these routes.
```

2023-11-10 01:04 UTC, GuySartorelli commented on en/04_Changelogs/5.2.0.md
> +Now, all of the controllers which handle these routes that come packaged in a core or supported module have configurable permissions that can be used to grant non-administrative users access to these
Done

2023-11-10 01:04 UTC, GuySartorelli commented on en/04_Changelogs/5.2.0.md
> +Previously, all `/dev/*` routes registered with [`DevelopmentAdmin`](api:SilverStripe\Dev\DevelopmentAdmin) (for example `/dev/tasks/MyBuildTask`) could only be access by administrator users, and thi
Done

2023-11-10 01:04 UTC, GuySartorelli commented on en/04_Changelogs/5.2.0.md
> +You can also now optonally implement a `canView()` method on your `BuildTask` implementations to restrict access for specific tasks even further. This means you can grant access to _some_ tasks to sp
Done

2023-11-10 01:05 UTC, GuySartorelli commented
> I think this page also needs to be updated: https://docs.silverstripe.org/en/5/developer_guides/controllers/builtin_middlewares/

What specific changes did you have in mind?

2023-11-10 01:42 UTC, andrewandante commented
> > I think this page also needs to be updated: https://docs.silverstripe.org/en/5/developer_guides/controllers/builtin_middlewares/
> 
> What specific changes did you have in mind?

Basically adding in a link to `DevelopmentAdminConfirmationMiddleware` along with the other ones, and a short description

2023-11-10 01:46 UTC, andrewandante approved these changes

2023-11-12 20:13 UTC, GuySartorelli commented
Added a row to the table on that page. Also added backticks to all items on that table.

2023-11-12 20:13 UTC, GuySartorelli commented on en/02_Developer_Guides/02_Controllers/06_Builtin_Middlewares.md
> +| [`DevelopmentAdminConfirmationMiddleware`](api:SilverStripe\Control\Middleware\DevelopmentAdminConfirmationMiddleware) | A specific subclass of `ConfirmationMiddleware` which handles the `/dev/*` r
This `DevelopmentAdminConfirmationMiddleware` row is the only new content on this page. Other than this, the only change was adding backticks.

2023-11-14 00:46 UTC, emteknetnz approved these changes

2023-11-14 00:46 UTC, merged