DOC Add SortPlugin to the docs
silverstripe/developer-docs pull request #408
Opened 2023-11-26 19:35 UTC by sabina-talipova

## Parent issue
-

2023-11-26 20:13 UTC, GuySartorelli requested changes

2023-11-26 20:13 UTC, GuySartorelli commented on en/02_Developer_Guides/19_GraphQL/02_working_with_dataobjects/02_query_plugins.md
> +In addition, you can use the custom sorting plugin ([`SortPlugin`](api:SilverStripe\GraphQL\Schema\Plugin\SortPlugin)) to sort fields that have `has_many` and `many_many` relationships. To do this, s
```suggestion
In addition, you can use the field sorting plugin ([`SortPlugin`](api:SilverStripe\GraphQL\Schema\Plugin\SortPlugin)) to sort fields that represent `has_many` and `many_many` relationships. To do this, simply add the desired fields to the query, as well as the `sort` argument to these fields. It is also necessary to update the scheme by adding a `sorter` plugin to those fields that need to be sorted. 
```

2023-11-26 21:16 UTC, sabina-talipova commented on en/02_Developer_Guides/19_GraphQL/02_working_with_dataobjects/02_query_plugins.md
> +In addition, you can use the custom sorting plugin ([`SortPlugin`](api:SilverStripe\GraphQL\Schema\Plugin\SortPlugin)) to sort fields that have `has_many` and `many_many` relationships. To do this, s
Updated

2023-11-27 21:00 UTC, GuySartorelli approved these changes
LGTM, will merge after the main PR is merged.

2023-11-27 23:19 UTC, merged