DOC linkfield accesibility improvements
silverstripe/developer-docs pull request #479
Opened 2024-03-13 01:54 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/245

2024-04-02 01:20 UTC, GuySartorelli requested changes

2024-04-02 01:20 UTC, GuySartorelli commented on en/08_Changelogs/5.3.0.md
> +- `silverstripe/linkfield` now has improved accesibilty support for screen readers and keyboard navigation. Also, focus states have been made consistent when using a keyboard or a mouse.
```suggestion
- `silverstripe/linkfield` now has improved accessibility support for screen readers and keyboard navigation. Focus states have also been made consistent between keyboard and mouse interaction.
```
The latter part of that is really just a subjective rewording so feel free to take or leave it - the main thing here is the typo for "accessibility"

2024-04-02 23:20 UTC, emteknetnz commented on en/08_Changelogs/5.3.0.md
> +- `silverstripe/linkfield` now has improved accesibilty support for screen readers and keyboard navigation. Also, focus states have been made consistent when using a keyboard or a mouse.
Updated

2024-04-03 20:49 UTC, GuySartorelli approved these changes
LGTM, will merge after the code is merged

2024-04-04 20:44 UTC, merged