MNT Move linting to a dedicated repository
silverstripe/developer-docs pull request #489
Opened 2024-04-02 04:14 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/.github/issues/206

2024-04-02 04:15 UTC, GuySartorelli commented on composer.json
> +            "name": "The Silverstripe Community",
Unrelated but was obviously wrong

2024-04-03 02:51 UTC, GuySartorelli commented on .github/workflows/lint-docs.yml
Renamed this file because it'll be added to the standardiser as an extra workflow for the other repos as well. So any repo that has `silverstripe/documentation-lint` as a dev dependency will have this workflow file added by standardiser.

2024-04-03 03:10 UTC, GuySartorelli commented on .github/workflows/lint-docs.yml
Ignore this - I've reverted the name change. I'll do it the same way that php linting is done for other repos. This will remain a special case.

2024-04-04 02:08 UTC, emteknetnz requested changes

2024-04-04 02:08 UTC, emteknetnz commented on .github/workflows/ci.yml
> +          FLAG="--with-${LINT_LANG#lint-}"
Please inline comment what `#lint-` does

2024-04-04 02:08 UTC, emteknetnz commented on .ss-docs-lint
> +en/
Rename to `.doclintrc`

2024-04-04 02:08 UTC, emteknetnz commented on .github/workflows/ci.yml
> +          vendor/bin/ss-docs-lint $FLAG
```suggestion
          vendor/bin/doclint $FLAG
```

2024-04-04 20:34 UTC, GuySartorelli commented on .github/workflows/ci.yml
> +          FLAG="--with-${LINT_LANG#lint-}"
Done

2024-04-04 20:34 UTC, GuySartorelli commented on .ss-docs-lint
> +en/
Done

2024-04-04 20:34 UTC, GuySartorelli commented on .github/workflows/ci.yml
> +          vendor/bin/ss-docs-lint $FLAG
Done

2024-04-04 21:01 UTC, emteknetnz approved these changes

2024-04-04 21:05 UTC, emteknetnz commented
Builds are red though expected to go green in the future once documentation-linting is in packagist

2024-04-04 21:05 UTC, merged