DOC Deprecate DataExtension and others
silverstripe/developer-docs pull request #563
Opened 2024-08-20 02:08 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/11050

2024-08-22 03:30 UTC, GuySartorelli requested changes

2024-08-22 03:30 UTC, GuySartorelli commented on en/08_Changelogs/5.3.0.md
> +- [`DataExtension`](api:SilverStripe\ORM\DataExtension), [`SiteTreeExtension`](api:SilverStripe\CMS\Model\SiteTreeExtension), and [`LeftAndMainExtension`](api:SilverStripe\Admin\LeftAndMainExtension)
```suggestion
- [`DataExtension`](api:SilverStripe\ORM\DataExtension), [`SiteTreeExtension`](api:SilverStripe\CMS\Model\SiteTreeExtension), and [`LeftAndMainExtension`](api:SilverStripe\Admin\LeftAndMainExtension) have been deprecated and will be removed in CMS 6.0. If you subclass any of these classes, you should now subclass [`Extension`](api:SilverStripe\Core\Extension) directly instead.
```

2024-08-25 21:51 UTC, emteknetnz commented on en/08_Changelogs/5.3.0.md
> +- [`DataExtension`](api:SilverStripe\ORM\DataExtension), [`SiteTreeExtension`](api:SilverStripe\CMS\Model\SiteTreeExtension), and [`LeftAndMainExtension`](api:SilverStripe\Admin\LeftAndMainExtension)
Updated

2024-08-25 21:56 UTC, GuySartorelli approved these changes
LGTM

2024-08-25 21:57 UTC, merged