DOC Rename TopPage classes
silverstripe/developer-docs pull request #575
Opened 2024-09-04 00:24 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-elemental/issues/1240

2024-09-04 05:14 UTC, GuySartorelli requested changes

2024-09-04 05:14 UTC, GuySartorelli commented on en/08_Changelogs/6.0.0.md
> +  - [Elemental TopPage class names changed](#elemental-top-page)
```suggestion
  - [Elemental `TopPage` class names changed](#elemental-top-page)
```

2024-09-04 23:13 UTC, emteknetnz commented on en/08_Changelogs/6.0.0.md
> +  - [Elemental TopPage class names changed](#elemental-top-page)
Updated

2024-09-10 04:24 UTC, GuySartorelli approved these changes
LGTM

2024-09-10 04:26 UTC, merged