DOC Remove configuration of _resources path
silverstripe/developer-docs pull request #58
Opened 2022-08-03 03:14 UTC by GuySartorelli

**NOTE** This PR assumes that https://github.com/silverstripe/developer-docs/pull/47 will be merged, and so it updates the `03_Upgrading/02_Upgrading_your_project.md` file from that PR.

The actual format of the upgrading docs can be sorted out closer to release - for now this serves as documentation of what breaking changes have been made.

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10399

2022-08-05 01:51 UTC, emteknetnz approved these changes

2022-08-08 00:19 UTC, emteknetnz requested changes
Very minor grammer changes

2022-08-08 00:19 UTC, emteknetnz commented on en/03_Upgrading/02_Upgrading_your_project.md
> +  - If your composer.json file already does not have a `extra.resources-dir` key and you want to keep your resources in the `resources` directory, you can set `extra.resources-dir` to "resources".
```suggestion
  - If your composer.json file already does not have an `extra.resources-dir` key and you want to keep your resources in the `resources` directory, you can set `extra.resources-dir` to "resources".
```

2022-08-08 00:19 UTC, emteknetnz commented on en/03_Upgrading/02_Upgrading_your_project.md
> +  - If your composer.json file already does not have a `extra.resources-dir` key and you want to use the new default `_resources` directory, you may need to check that your code and templates don't a
```suggestion
  - If your composer.json file already does not have an `extra.resources-dir` key and you want to use the new default `_resources` directory, you may need to check that your code and templates don't assume the directory name for those resources. In your templates it is preferred to [use `$resourePath()` or `$resourceURL()`](developer_guides/templates/requirements/#direct-resource-urls) to get paths for resources.
```

2022-08-08 05:22 UTC, GuySartorelli commented on en/03_Upgrading/02_Upgrading_your_project.md
> +  - If your composer.json file already does not have a `extra.resources-dir` key and you want to keep your resources in the `resources` directory, you can set `extra.resources-dir` to "resources".
done

2022-08-08 05:23 UTC, GuySartorelli commented on en/03_Upgrading/02_Upgrading_your_project.md
> +  - If your composer.json file already does not have a `extra.resources-dir` key and you want to use the new default `_resources` directory, you may need to check that your code and templates don't a
done

2022-08-08 22:32 UTC, emteknetnz approved these changes

2022-08-08 22:32 UTC, merged