DOC Document GridFieldFilterHeader primary field customisation
silverstripe/developer-docs pull request #6
Opened 2022-07-07 21:54 UTC by GuySartorelli

Docs for https://github.com/silverstripe/silverstripe-framework/pull/9341

## Notes
- Assumes https://github.com/silverstripe/silverstripe-framework/pull/10382 will be merged in first. There will likely be some merge conflict with that PR.

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/9356

2022-07-12 00:33 UTC, emteknetnz requested changes
I'm thinking close this one and add an allowlist style config into https://github.com/silverstripe/silverstripe-framework/pull/10382 would be better

2022-07-25 05:34 UTC, GuySartorelli commented
We came to the decision not to use an allow-list configuration in the end: https://github.com/silverstripe/silverstripe-framework/pull/10382#issuecomment-1181240324

2022-08-01 01:05 UTC, GuySartorelli commented
Rebased and resolved conflict

2022-08-01 23:58 UTC, emteknetnz approved these changes

2022-08-01 23:58 UTC, merged