DOC Update changelog with list interface changes
silverstripe/developer-docs pull request #605
Opened 2024-10-23 00:32 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/8778

2024-10-24 20:58 UTC, GuySartorelli requested changes
Just a minor readability change

2024-10-24 20:58 UTC, GuySartorelli commented on en/08_Changelogs/6.0.0.md
> +Many of the methods on `SS_List` are now strongly typed, along with the classes that implement it. This means that you will need to ensure that any custom classes that implement `SS_List` have the co
```suggestion
Many of the methods on `SS_List` and the classes that implement it are now strongly typed. This means that you will need to ensure that any custom classes that implement `SS_List` have the correct types for the methods that they implement.
```

2024-10-24 21:00 UTC, emteknetnz commented on en/08_Changelogs/6.0.0.md
> +Many of the methods on `SS_List` are now strongly typed, along with the classes that implement it. This means that you will need to ensure that any custom classes that implement `SS_List` have the co
Updated

2024-10-29 21:23 UTC, GuySartorelli approved these changes

2024-10-30 01:23 UTC, merged