DOC Adding missing quote on routing example
silverstripe/developer-docs pull request #617
Opened 2024-11-01 11:57 UTC by catharsisjelly

## Description
Found a missing quote in the documentation for routing

## Issues
- #611 

## Pull request checklist
- [x] The target branch is correct
    - See [branches and commit messages](https://docs.silverstripe.org/en/contributing/documentation#branches-and-commit-messages)
- [x] All commits are relevant to the purpose of the PR (e.g. no TODO comments, unrelated rewording/restructuring, or arbitrary changes)
    - Small amounts of additional changes are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/documentation/)
- [x] The changes follow our [writing style guide](https://docs.silverstripe.org/en/contributing/documentation/#writing-style)
- [x] Code examples follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] CI is green

2024-11-01 11:59 UTC, catharsisjelly commented
A resubmit of #612 as I messed it up, this is now using the right branch. Let me know if you want any changes.

2024-11-03 20:28 UTC, GuySartorelli requested changes
Thanks. Minor change - the colon is part of YAML syntax, not part of the string.

2024-11-03 20:28 UTC, GuySartorelli commented on en/02_Developer_Guides/02_Controllers/02_Routing.md
> +    'admin/help//$Action/$ID:' 'App\Control\AdminHelpController'
```suggestion
    'admin/help//$Action/$ID': 'App\Control\AdminHelpController'
```

2024-11-04 20:15 UTC, GuySartorelli approved these changes
LGTM, thanks again

2024-11-04 20:15 UTC, merged