DOC Document symfony 6 dependency changes
silverstripe/developer-docs pull request #79
Opened 2022-09-05 22:26 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10389

2022-09-06 22:50 UTC, GuySartorelli requested changes
I think the docs changes from https://github.com/silverstripe/silverstripe-framework/pull/10187/files are needed here as well.

2022-09-07 02:38 UTC, emteknetnz commented
Have added changes

2022-09-07 22:41 UTC, GuySartorelli requested changes
Looks like there are still other mentions of the old classes, e.g. in https://docs.silverstripe.org/en/4/developer_guides/performance/caching
> Clearing caches by namespace is dependent on the used adapter: While the `FilesystemCache` adapter clears only the namespaced cache, a `MemcachedCache` adapter will clear all caches regardless of namespace, since the underlying memcached service doesn't support this. See "Invalidation" for alternative strategies.

There's also at least one link to symfony 5 docs (https://github.com/symfony/cache/tree/5.x/Adapter)

Might pay to do a word search for any of the old cache names, and for any mention of symfony to make sure we have no outdated references.

2022-09-07 23:48 UTC, emteknetnz commented on en/02_Developer_Guides/08_Performance/01_Caching.md
> - * [ClassManifest](api:SilverStripe\Core\Manifest\ClassManifest) and [ThemeManifest](api:SilverStripe\View\ThemeManifest)
Have removed references to Config + Class manifests because they're not hardcoded to use a particular type of cache

2022-09-07 23:49 UTC, emteknetnz commented
@GuySartorelli Have updated

2022-09-08 00:00 UTC, GuySartorelli approved these changes

2022-09-08 00:00 UTC, merged