DOC Document SecurityAdmin extending ModelAdmin
silverstripe/developer-docs pull request #80
Opened 2022-09-07 02:31 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1350

2022-09-08 00:11 UTC, GuySartorelli requested changes

2022-09-08 00:11 UTC, ChloeSartorelli commented on en/04_Changelogs/5.0.0.md
> +- SecurityAdmin now extends ModelAdmin instead of LeftAndMain. This was done to remove duplicate code.
Probably want more details in here than that - e.g. some paths will be changing, extension hooks are likely to have changed, etc.

2022-09-14 03:02 UTC, GuySartorelli commented
Rebased on `5` as a part of https://github.com/silverstripe/developer-docs/issues/74 - but the review still stands.

2022-09-15 03:27 UTC, emteknetnz commented on en/04_Changelogs/5.0.0.md
> +- SecurityAdmin now extends ModelAdmin instead of LeftAndMain. This was done to remove duplicate code.
Updated.  I don't think the changes in path are probably too much details as they're more of a UX thing.

2022-09-15 22:57 UTC, GuySartorelli commented on en/04_Changelogs/5.0.0.md
> +- SecurityAdmin now extends ModelAdmin instead of LeftAndMain. This was done to remove duplicate code.
The changes in paths may have implications for customisations that call custom actions in extensions, for example.

2022-09-19 00:10 UTC, emteknetnz commented on en/04_Changelogs/5.0.0.md
> +- SecurityAdmin now extends ModelAdmin instead of LeftAndMain. This was done to remove duplicate code.
Updated

2022-09-19 02:22 UTC, GuySartorelli commented on en/04_Changelogs/5.0.0.md
> +  - Previous extension hook implementations of `SecurityAdmin::updateEditForm($form)` should still work as the extension hook is called in `ModelAdmin::getEditForm()`
The actual form is slightly different so the extensions may need to be reworked slightly to work with the way modeladmin's form is produced.... but we can work out the exact wording for that closer to release. For now this is good enough.

2022-09-19 02:22 UTC, GuySartorelli approved these changes

2022-09-19 02:22 UTC, merged